apiVersion: v1
kind: Service
metadata:
  name: react-web
spec:
  selector:
    app: react-web
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-web
  template:
    metadata:
      labels:
        app: react-web
    spec:
      containers:
        - name: react-web
          image: spring-data-rest-web:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
